const { expect } = require("chai");
const { apiClient } = require("./utils");
const axiosInstance = require("../../utils/axios-instance");
const allure = require("@wdio/allure-reporter").default;
describe("Authors API - POST /Authors", () => {
  it("should add a new author to the system", async () => {
    allure.addFeature("Authors API");
    allure.addStory("POST /Authors");
    allure.addSeverity("critical");

    const newAuthor = {
      id: 0, // ID will be generated by the system
      idBook: 1,
      firstName: "John",
      lastName: "Doe",
    };

    const response = await apiClient.post("/Authors", newAuthor);
    expect(response.status).to.equal(200);
    expect(response.data).to.have.property("firstName", newAuthor.firstName);
  });
});
