name: ApiautomationCI

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A job to run the tests
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx wdio run wdio.conf.js


      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
